kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: s2i-java:latest
  SourceLocation: ./
  SourceType: local
  Ports:
  - 9779/TCP
  - 8080/TCP
  - 8778/TCP
  Application: posts-app
  Project: posts-app
  Name: quarkus-backend
  Envs:
  - Name: JAVA_OPTIONS
    Value: -Dquarkus.http.host=0.0.0.0
  - Name: JAVA_APP_JAR
    Value: quarkus-backend-1.0.0-SNAPSHOT-runner.jar
  Url:
  - Name: backend
    Port: 8080
